# 00. Pytorch Fundamental

## Import Libraries


In [ ]:
import numpy as np
import torch
print(torch.__version__)

2.0.1+cu118


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## 1 Create Tensor

### 1.1 From existed data
torch.
* tensor()
* assarray()
* as_tensor()
* from_numpy()


In [ ]:
scalar = torch.tensor(data = 10,
                      dtype=torch.float32, # data type
                      device = 'cpu',      # used on cpu device
                      requires_grad=False) # not record operation on the tensor
print(f"SCALAR:\n{scalar}\nNumber of dimention: {scalar.ndim}\nShape: {scalar.shape}")

SCALAR:
10.0
Number of dimention: 0
Shape: torch.Size([])


In [ ]:
vector = torch.tensor([1, 2, 3])
print(f"VECTOR:\n{vector}\nNumber of dimention: {vector.ndim}\nShape: {vector.shape}")

VECTOR:
tensor([1, 2, 3])
Number of dimention: 1
Shape: torch.Size([3])


In [ ]:
MATRIX = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
print(f"MATRIX:\n{MATRIX}\nNumber of dimention: {MATRIX.ndim}\nShape: {MATRIX.shape}")

MATRIX:
tensor([[1, 2, 3],
        [4, 5, 6]])
Number of dimention: 2
Shape: torch.Size([2, 3])


In [ ]:
Tensor = torch.Tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],
                       [[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
print(f"TENSOR:\n {Tensor}\nNumber of dimention: {Tensor.ndim}\nShape: {Tensor.shape}")

TENSOR:
 tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]],

        [[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])
Number of dimention: 3
Shape: torch.Size([2, 3, 3])


In [ ]:
# torch.assarray()
np_array = np.array([[1, 2, 3],
                     [4, 5, 6]])
ts = torch.asarray(obj=np_array,
                   dtype=None, # data type: datatype of np_array
                   device = None,# default: cpu
                   copy=None, # whether share memory: default -> true
                   requires_grad=False) # require gradient -> default false
ts[0, 0] = -1
print(np_array)

np_array = np.array([[1, 2, 3],
                     [4, 5, 6]])
ts = torch.asarray(obj=np_array,
                   copy=True)
ts[0, 0] = -1
print(np_array)

[[-1  2  3]
 [ 4  5  6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
# torch.from_numpy() - Share memory

np_array = np.array([[1, 2, 3],
                     [4, 5, 6]])

ts = torch.from_numpy(np_array)
ts.reshape((3, 2)), ts

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([[1, 2, 3],
         [4, 5, 6]]))

### 1.3 Specified Tensor

`torch.`
* `ones()` / `one_like()`
* `zeros()` / `zeros_like()`
* `arange()`
* `linspace()`
* `logspace()`
* `eye()`
* `empty()` / `empty_like()`
* `full()` / `full_like()`
* `empty() / empty_like()`

...

In [ ]:
# ones()
ones_tensor = torch.ones((2, 3))
print(f'{ones_tensor}\nndim: {ones_tensor.ndim}\nShape: {ones_tensor.shape}')

tensor([[1., 1., 1.],
        [1., 1., 1.]])
ndim: 2
Shape: torch.Size([2, 3])


In [ ]:
zeros_tensor = torch.zeros((2, 3))
print(f'{zeros_tensor}\nndim: {zeros_tensor.ndim}\nShape: {zeros_tensor.shape}')

tensor([[0., 0., 0.],
        [0., 0., 0.]])
ndim: 2
Shape: torch.Size([2, 3])


In [ ]:
arange_tensor = torch.arange(start = 0, end = 11, step = 2) # create a range tensor from 0 to 10 with step 2
print(f'{arange_tensor}\nndim: {arange_tensor.ndim}\nShape: {arange_tensor.shape}')

tensor([ 0,  2,  4,  6,  8, 10])
ndim: 1
Shape: torch.Size([6])


In [ ]:
linspace_tensor = torch.linspace(start = 1, end = 2, steps=3) # step from 1 to 2 with 3 steps
print(f'{linspace_tensor}\nndim: {linspace_tensor.ndim}\nShape: {linspace_tensor.shape}')

tensor([1.0000, 1.5000, 2.0000])
ndim: 1
Shape: torch.Size([3])


In [ ]:
# logspace()
logspace_ts = torch.logspace(start=1, end= 10, steps=10, base= 2)
print(logspace_ts)

tensor([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512., 1024.])


In [ ]:
# spuare matrix
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
minus_on_tensor = torch.full(size=(2, 3), fill_value=-1)
print(f'{minus_on_tensor}\nndim: {minus_on_tensor.ndim}\nShape: {minus_on_tensor.shape}')

tensor([[-1, -1, -1],
        [-1, -1, -1]])
ndim: 2
Shape: torch.Size([2, 3])


In [ ]:
# Create empty tensor -> uninitialized data
empty_tensor = torch.empty(size=(2, 3))
print(empty_tensor, empty_tensor.dtype)

tensor([[-2.4646e+31,  3.1184e-41, -2.9051e+31],
        [ 3.1184e-41,  1.1210e-43,  0.0000e+00]]) torch.float32


### 1.2 By Random
`torch.`
* `seed()`, `manual_seed()`
* `rand()`, `rand_like()` -> uniform dist [0, 1)
* `randint()`, randint_like() -> uniform dist [low, hight)
* `randn()`, `randn_like()` -> normal dist (mean = 0, std = 1)



In [ ]:
# random tensor contain elements in [0, 1)
random_tensor = torch.rand((2, 3))  # generate from uniform distribution
print(f'{random_tensor}\nndim: {random_tensor.ndim}\nShape: {random_tensor.shape}')

tensor([[0.9235, 0.9039, 0.9208],
        [0.4939, 0.4267, 0.3904]])
ndim: 2
Shape: torch.Size([2, 3])


In [ ]:
torch.manual_seed(1)
random_tensor = torch.rand((2, 3))  # generate from uniform distribution
print(f'{random_tensor}\nndim: {random_tensor.ndim}\nShape: {random_tensor.shape}')

torch.manual_seed(1)
random_tensor = torch.rand((2, 3))  # generate from uniform distribution
print(f'{random_tensor}\nndim: {random_tensor.ndim}\nShape: {random_tensor.shape}')

tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999]])
ndim: 2
Shape: torch.Size([2, 3])
tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999]])
ndim: 2
Shape: torch.Size([2, 3])


In [ ]:
# random tensor contain integer elements in [low, hight)
random_tensor = torch.randint(-10, 10, (2, 3))  # generate from uniform distribution
print(f'{random_tensor}\nndim: {random_tensor.ndim}\nShape: {random_tensor.shape}')

tensor([[ 1, -9,  9],
        [ 2, -2, -1]])
ndim: 2
Shape: torch.Size([2, 3])


In [ ]:
# random tentor contain elements generate from N(0, 1)
random_tensor = torch.randn((2, 3))
print(f'{random_tensor}\nndim: {random_tensor.ndim}\nShape: {random_tensor.shape}')

tensor([[-1.5228,  0.3817, -1.0276],
        [-0.5631, -0.8923, -0.0583]])
ndim: 2
Shape: torch.Size([2, 3])


In [ ]:
# create tensor by random
random_tensor = torch.randn(size=(2, 3))
print(random_tensor)

# get important attributes of the tensor
dimention = random_tensor.ndim
shape = random_tensor.shape
data_type = random_tensor.dtype
device = random_tensor.device
layout = random_tensor.layout
is_grad = random_tensor.requires_grad

print(f"Dimention: {dimention}")
print(f'Shape: {shape}')
print(f'Data type: {data_type}')
print(f'device: {device}')
print(f'Is gradient: {is_grad}')
print(f'Layout: {layout}')

tensor([[-0.1955, -0.9656,  0.4224],
        [ 0.2673, -0.4212, -0.5107]])
Dimention: 2
Shape: torch.Size([2, 3])
Data type: torch.float32
device: cpu
Is gradient: False
Layout: torch.strided


## 2 Tensor Operations




### 2.1 Poitwise Ops

* Addition
* Subtraction
* Division
* Multiplication
* Dot product
* Absolute
* sin/cos/tan/arcsin/arccos/arctan
* bitwise_not/bitwise_and/ bitwise_or/bitwise_xor
* ceil/floor/round
* clamp
* exp/log/pow/rsqrt/square

In [ ]:
# addition/subtraction/division/multiplication
ts_1 = torch.randn(size=(2, 3))
ts_2 = torch.randn(size=(2, 3))
add_1_2 = torch.add(ts_1, ts_2)
sub_1_2 = torch.sub(ts_1, ts_2)
div_1_2 = torch.div(ts_1, ts_2)
mul_1_2 = torch.mul(ts_1, ts_2)

print(f"tensor 1:\n {ts_1}")
print(f"tensor 2:\n {ts_2}")
print(f"tensor 1 + tensor 2:\n {add_1_2}")
print(f"tensor 1 - tensor 2:\n {sub_1_2}")
print(f"tensor 1 * tensor 2:\n {mul_1_2}")
print(f"tensor 1 / tensor 2:\n {div_1_2}")

tensor 1:
 tensor([[-1.3459,  0.5119, -0.6933],
        [-0.1668, -0.9999, -1.6476]])
tensor 2:
 tensor([[ 0.8098,  0.0554,  1.1340],
        [-0.5326,  0.6592, -1.5964]])
tensor 1 + tensor 2:
 tensor([[-0.5361,  0.5673,  0.4407],
        [-0.6994, -0.3407, -3.2440]])
tensor 1 - tensor 2:
 tensor([[-2.1557,  0.4565, -1.8273],
        [ 0.3659, -1.6591, -0.0512]])
tensor 1 * tensor 2:
 tensor([[-1.0899,  0.0284, -0.7862],
        [ 0.0888, -0.6591,  2.6302]])
tensor 1 / tensor 2:
 tensor([[-1.6619,  9.2360, -0.6114],
        [ 0.3131, -1.5168,  1.0321]])


In [ ]:
# Dot product
ts_1 = torch.randn(size=(2, 3))
ts_2 = torch.randn(size=(3, 2))
matmul = torch.matmul(ts_1, ts_2)
print(matmul, matmul.shape, matmul.dtype)

tensor([[-0.7083,  1.3544],
        [-0.4831,  1.0310]]) torch.Size([2, 2]) torch.float32


In [ ]:
# clamp all elements into the range [min, max]
ts = torch.randint(0, 10, size=(20,))
clamped_ts = torch.clamp(ts, 4, 7)
print(f'  Input tensor: {ts}\nclamped tensor: {clamped_ts}')

  Input tensor: tensor([2, 9, 5, 4, 2, 3, 7, 7, 9, 7, 1, 9, 2, 4, 8, 8, 6, 8, 8, 3])
clamped tensor: tensor([4, 7, 5, 4, 4, 4, 7, 7, 7, 7, 4, 7, 4, 4, 7, 7, 6, 7, 7, 4])


### 2.2 Reduction Ops
* min/max
* amin/amax
* argmin/argmax
* all/any
* mean/median/std/var
* unique/sum/count_nonzero
...


In [ ]:
ts = torch.randint(low=-10, high=10, size=(2, 10))
min_ts = torch.min(ts)
max_ts = torch.max(ts)
amin_d_0 = torch.amin(ts, dim=0, keepdim=True)
amin_d_1 = torch.amin(ts, dim=1, keepdim=True)
all = torch.all(ts)
any = torch.any(ts)
unique = torch.unique(ts)
count_nonzero = torch.count_nonzero(ts)
print(ts)
print(f'min: {min_ts}, max: {max_ts},\n amin_0: {amin_d_0}, \
      amin_1: {amin_d_1},\n all: {all}, any: {any},\n unique: {unique}, count_nonzero: {count_nonzero}')


tensor([[ 6, -5, -4,  2,  1, -2, -2,  0,  1, -9],
        [ 3,  3, -2,  6, -6,  8, -9, -8,  5,  9]])
min: -9, max: 9,
 amin_0: tensor([[ 3, -5, -4,  2, -6, -2, -9, -8,  1, -9]]),       amin_1: tensor([[-9],
        [-9]]),
 all: False, any: True,
 unique: tensor([-9, -8, -6, -5, -4, -2,  0,  1,  2,  3,  5,  6,  8,  9]), count_nonzero: 19


### 2.3 Comparision Ops

* `allclose()`-> check input and another
* `sort()`
* `argsort()` -> sort by value and dimention, return indices
* `ep(), ge(), gt(), lt(), ne()`
* `equal()`
* `maximun(), minimum()`


### 2.4 Other Operations

* `clone()`
* `cumsum(), cummax(), cummin(), cumprod()`
* `flatten(), flip()`


## 3 Indexing, Slicing, Joinging, Mutating Ops

* `cat()`
* `chunk()`
* `split(), stack()`
* `dsplit(), hsplit(), vsplit()`
* `dstack(), hstack(), vstack()`
* `squeeze(), unsqueeze()`
* `permute()`
* `reshape()`
* `where()`

## 4 Context manager enable or disable gradients

* `with torch.inference_mode(mode=True)`
* `with torch.no_grad()`
* `with torch.enable_grad()`


In [ ]:
x = torch.tensor(5., requires_grad=True)
with torch.inference_mode():
  y = x * x + 2

print(x, x.requires_grad)
print(y, y.requires_grad)


tensor(5., requires_grad=True) True
tensor(27.) False
